"""
Theme definitions for the Farmer CLI application.

This module contains all UI theme configurations for Rich styling,
including border styles, color palettes, and visual elements.
"""

from typing import Any
from typing import Dict


# Border character sets
SINGLE_LINE: Dict[str, str] = {
    "top_left": "┌",
    "top_right": "┐",
    "bottom_left": "└",
    "bottom_right": "┘",
    "horizontal": "─",
    "vertical": "│",
    "cross": "┼",
    "t_down": "┬",
    "t_up": "┴",
    "t_right": "├",
    "t_left": "┤",
}

DOUBLE_LINE: Dict[str, str] = {
    "top_left": "╔",
    "top_right": "╗",
    "bottom_left": "╚",
    "bottom_right": "╝",
    "horizontal": "═",
    "vertical": "║",
    "cross": "╬",
    "t_down": "╦",
    "t_up": "╩",
    "t_right": "╠",
    "t_left": "╣",
}

ROUNDED_LINE: Dict[str, str] = {
    "top_left": "╭",
    "top_right": "╮",
    "bottom_left": "╰",
    "bottom_right": "╯",
    "horizontal": "─",
    "vertical": "│",
    "cross": "┼",
    "t_down": "┬",
    "t_up": "┴",
    "t_right": "├",
    "t_left": "┤",
}

HEAVY_LINE: Dict[str, str] = {
    "top_left": "┏",
    "top_right": "┓",
    "bottom_left": "┗",
    "bottom_right": "┛",
    "horizontal": "━",
    "vertical": "┃",
    "cross": "╋",
    "t_down": "┳",
    "t_up": "┻",
    "t_right": "┣",
    "t_left": "┫",
}

ASCII_LINE: Dict[str, str] = {
    "top_left": "+",
    "top_right": "+",
    "bottom_left": "+",
    "bottom_right": "+",
    "horizontal": "-",
    "vertical": "|",
    "cross": "+",
    "t_down": "+",
    "t_up": "+",
    "t_right": "+",
    "t_left": "+",
}

# Theme definitions with expanded visual properties
THEMES: Dict[str, Dict[str, Any]] = {
    "default": {
        "name": "Default",
        "description": "Classic terminal aesthetic with vibrant colors",
        "border_style": "bold magenta",
        "border_chars": DOUBLE_LINE,
        "title_style": "bold cyan",
        "subtitle_style": "cyan",
        "option_style": "bold white",
        "option_number_style": "bold yellow",
        "highlight_style": "bold yellow",
        "success_style": "bold green",
        "error_style": "bold red",
        "warning_style": "bold yellow",
        "info_style": "bold blue",
        "prompt_style": "bold cyan",
        "header_style": "bold magenta on black",
        "footer_style": "dim white",
        "table_header_style": "bold white on blue",
        "table_row_style": "white",
        "table_alt_row_style": "bright_black",
        "progress_bar_complete": "bold green",
        "progress_bar_incomplete": "dim white",
        "spinner_style": "bold cyan",
        "code_style": "bright_white on black",
        "code_line_numbers": "dim cyan",
    },
    "dark": {
        "name": "Dark Mode",
        "description": "Sleek dark theme for reduced eye strain",
        "border_style": "white",
        "border_chars": SINGLE_LINE,
        "title_style": "bold bright_green",
        "subtitle_style": "green",
        "option_style": "bright_white",
        "option_number_style": "bold bright_cyan",
        "highlight_style": "bold bright_red",
        "success_style": "bold bright_green",
        "error_style": "bold bright_red",
        "warning_style": "bold bright_yellow",
        "info_style": "bold bright_cyan",
        "prompt_style": "bright_cyan",
        "header_style": "bold white on grey23",
        "footer_style": "grey50",
        "table_header_style": "bold bright_white on grey35",
        "table_row_style": "grey85",
        "table_alt_row_style": "grey70",
        "progress_bar_complete": "bright_green",
        "progress_bar_incomplete": "grey35",
        "spinner_style": "bright_cyan",
        "code_style": "bright_white on grey15",
        "code_line_numbers": "grey50",
    },
    "light": {
        "name": "Light Mode",
        "description": "Clean and bright theme for well-lit environments",
        "border_style": "black",
        "border_chars": ROUNDED_LINE,
        "title_style": "bold blue",
        "subtitle_style": "blue",
        "option_style": "black",
        "option_number_style": "bold blue",
        "highlight_style": "bold magenta",
        "success_style": "bold green",
        "error_style": "bold red",
        "warning_style": "bold yellow",
        "info_style": "bold blue",
        "prompt_style": "blue",
        "header_style": "bold black on bright_white",
        "footer_style": "grey50",
        "table_header_style": "bold white on blue",
        "table_row_style": "black",
        "table_alt_row_style": "grey35",
        "progress_bar_complete": "blue",
        "progress_bar_incomplete": "grey85",
        "spinner_style": "blue",
        "code_style": "black on grey93",
        "code_line_numbers": "grey50",
    },
    "high_contrast": {
        "name": "High Contrast",
        "description": "Maximum contrast for accessibility",
        "border_style": "bold bright_white",
        "border_chars": HEAVY_LINE,
        "title_style": "bold bright_yellow",
        "subtitle_style": "bright_yellow",
        "option_style": "bold bright_white",
        "option_number_style": "bold bright_cyan",
        "highlight_style": "bold bright_cyan on black",
        "success_style": "bold bright_green",
        "error_style": "bold bright_red",
        "warning_style": "bold bright_yellow",
        "info_style": "bold bright_white",
        "prompt_style": "bold bright_yellow",
        "header_style": "bold bright_yellow on black",
        "footer_style": "bright_white",
        "table_header_style": "bold black on bright_white",
        "table_row_style": "bright_white",
        "table_alt_row_style": "bright_white",
        "progress_bar_complete": "bright_green",
        "progress_bar_incomplete": "bright_white",
        "spinner_style": "bright_yellow",
        "code_style": "bright_white on black",
        "code_line_numbers": "bright_yellow",
    },
    "ocean": {
        "name": "Ocean",
        "description": "Calming blue and teal palette",
        "border_style": "cyan",
        "border_chars": ROUNDED_LINE,
        "title_style": "bold bright_cyan",
        "subtitle_style": "cyan",
        "option_style": "bright_blue",
        "option_number_style": "bold turquoise2",
        "highlight_style": "bold sky_blue1",
        "success_style": "bold sea_green2",
        "error_style": "bold salmon1",
        "warning_style": "bold gold1",
        "info_style": "bold dodger_blue2",
        "prompt_style": "turquoise2",
        "header_style": "bold bright_white on deep_sky_blue4",
        "footer_style": "steel_blue",
        "table_header_style": "bold white on dark_cyan",
        "table_row_style": "pale_turquoise1",
        "table_alt_row_style": "light_cyan3",
        "progress_bar_complete": "cyan",
        "progress_bar_incomplete": "steel_blue",
        "spinner_style": "bright_cyan",
        "code_style": "bright_white on navy_blue",
        "code_line_numbers": "steel_blue1",
    },
    "forest": {
        "name": "Forest",
        "description": "Natural green tones inspired by nature",
        "border_style": "green",
        "border_chars": SINGLE_LINE,
        "title_style": "bold bright_green",
        "subtitle_style": "green",
        "option_style": "spring_green2",
        "option_number_style": "bold chartreuse2",
        "highlight_style": "bold yellow2",
        "success_style": "bold bright_green",
        "error_style": "bold indian_red1",
        "warning_style": "bold orange3",
        "info_style": "bold spring_green1",
        "prompt_style": "chartreuse3",
        "header_style": "bold bright_white on dark_green",
        "footer_style": "dark_olive_green3",
        "table_header_style": "bold white on dark_green",
        "table_row_style": "honeydew2",
        "table_alt_row_style": "dark_sea_green",
        "progress_bar_complete": "green",
        "progress_bar_incomplete": "dark_olive_green3",
        "spinner_style": "bright_green",
        "code_style": "bright_white on grey11",
        "code_line_numbers": "dark_olive_green2",
    },
    "neon": {
        "name": "Neon",
        "description": "Vibrant cyberpunk-inspired theme",
        "border_style": "bold magenta",
        "border_chars": DOUBLE_LINE,
        "title_style": "bold hot_pink",
        "subtitle_style": "deep_pink2",
        "option_style": "bold orchid1",
        "option_number_style": "bold cyan1",
        "highlight_style": "bold yellow1 on purple4",
        "success_style": "bold green1",
        "error_style": "bold red1",
        "warning_style": "bold yellow1",
        "info_style": "bold dodger_blue1",
        "prompt_style": "bold hot_pink",
        "header_style": "bold bright_white on purple4",
        "footer_style": "medium_purple",
        "table_header_style": "bold bright_white on deep_pink4",
        "table_row_style": "plum1",
        "table_alt_row_style": "medium_purple3",
        "progress_bar_complete": "hot_pink",
        "progress_bar_incomplete": "purple4",
        "spinner_style": "bold magenta1",
        "code_style": "bright_white on grey7",
        "code_line_numbers": "medium_purple",
    },
    "monochrome": {
        "name": "Monochrome",
        "description": "Elegant grayscale theme",
        "border_style": "white",
        "border_chars": SINGLE_LINE,
        "title_style": "bold bright_white",
        "subtitle_style": "grey85",
        "option_style": "grey93",
        "option_number_style": "bold bright_white",
        "highlight_style": "reverse",
        "success_style": "bold bright_white",
        "error_style": "bold bright_white reverse",
        "warning_style": "bold grey85",
        "info_style": "bright_white",
        "prompt_style": "bold bright_white",
        "header_style": "bold bright_white on grey23",
        "footer_style": "grey58",
        "table_header_style": "bold bright_white on grey35",
        "table_row_style": "grey85",
        "table_alt_row_style": "grey70",
        "progress_bar_complete": "bright_white",
        "progress_bar_incomplete": "grey35",
        "spinner_style": "bright_white",
        "code_style": "bright_white on grey15",
        "code_line_numbers": "grey50",
    },
    "retro": {
        "name": "Retro Terminal",
        "description": "Classic amber/green phosphor terminal",
        "border_style": "yellow2",
        "border_chars": ASCII_LINE,
        "title_style": "bold yellow2",
        "subtitle_style": "dark_goldenrod",
        "option_style": "gold3",
        "option_number_style": "bold orange1",
        "highlight_style": "bold yellow2 reverse",
        "success_style": "bold yellow2",
        "error_style": "bold orange_red1",
        "warning_style": "bold dark_orange",
        "info_style": "gold1",
        "prompt_style": "bold yellow2",
        "header_style": "bold yellow2 on grey11",
        "footer_style": "dark_goldenrod",
        "table_header_style": "bold black on yellow2",
        "table_row_style": "gold3",
        "table_alt_row_style": "dark_goldenrod",
        "progress_bar_complete": "yellow2",
        "progress_bar_incomplete": "grey23",
        "spinner_style": "bold yellow2",
        "code_style": "yellow2 on black",
        "code_line_numbers": "dark_goldenrod",
    },
}

# Visual element definitions
VISUAL_ELEMENTS: Dict[str, str] = {
    # Progress indicators
    "progress_filled": "█",
    "progress_empty": "░",
    "progress_partial": "▒",
    # Arrows and pointers
    "arrow_right": "→",
    "arrow_left": "←",
    "arrow_up": "↑",
    "arrow_down": "↓",
    "triangle_right": "▶",
    "triangle_left": "◀",
    "triangle_up": "▲",
    "triangle_down": "▼",
    # Status indicators
    "bullet": "•",
    "circle": "○",
    "filled_circle": "●",
    "square": "□",
    "filled_square": "■",
    "check": "✓",
    "cross": "✗",
    "star": "★",
    "star_empty": "☆",
    # Separators
    "dot_separator": "·",
    "dash_separator": "—",
    "vertical_separator": "│",
    "horizontal_separator": "─",
    # Decorative elements
    "corner_top_left": "┌",
    "corner_top_right": "┐",
    "corner_bottom_left": "└",
    "corner_bottom_right": "┘",
    "branch": "├",
    "branch_end": "└",
}

# ASCII fallback for limited terminals
ASCII_ELEMENTS: Dict[str, str] = {
    "progress_filled": "#",
    "progress_empty": "-",
    "progress_partial": "=",
    "arrow_right": "->",
    "arrow_left": "<-",
    "arrow_up": "^",
    "arrow_down": "v",
    "triangle_right": ">",
    "triangle_left": "<",
    "triangle_up": "^",
    "triangle_down": "v",
    "bullet": "*",
    "circle": "o",
    "filled_circle": "@",
    "square": "[]",
    "filled_square": "[X]",
    "check": "[v]",
    "cross": "[x]",
    "star": "*",
    "star_empty": "-",
    "dot_separator": ".",
    "dash_separator": "--",
    "vertical_separator": "|",
    "horizontal_separator": "-",
    "corner_top_left": "+",
    "corner_top_right": "+",
    "corner_bottom_left": "+",
    "corner_bottom_right": "+",
    "branch": "+",
    "branch_end": "+",
}

# Application-specific help texts
HELP_TEXTS: Dict[str, str] = {
    "data_processing": (
        "Access powerful data manipulation tools including code display, system information, data tables, "
        "and progress tracking."
    ),
    "user_management": (
        "Manage application users - add new users, view existing users, and export user data in various formats."
    ),
    "configuration": (
        "Customize your experience with themes, display settings, time formats, and searchable help documentation."
    ),
    "system_tools": (
        "System utilities including file browser, weather information, documentation export, and feedback submission."
    ),
    "exit": "Save your work and exit the application safely.",
    "theme_selection": "Choose from multiple visual themes to personalize your terminal experience.",
    "navigation": "Use number keys to select options, Enter to confirm, and 0 to go back.",
}
